In [2]:
import numpy as np

In [7]:
a = np.array([1.0, 2.0, 3.0])
b = np.array([1, -1, 0])
print(a)
print(b)

[1. 2. 3.]
[ 1 -1  0]


In [4]:
a.dtype, b.dtype

(dtype('float64'), dtype('int64'))

In [5]:
a[0], b[1]

(1.0, -1)

In [9]:
np.array([0, 0, 0]) / 0

/home/zhukovgreen/.cache/pypoetry/virtualenvs/np-py3.7/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan, nan, nan])

In [11]:
np.array([1, 0, 0]) / np.array([0, 0, 0])

/home/zhukovgreen/.cache/pypoetry/virtualenvs/np-py3.7/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
/home/zhukovgreen/.cache/pypoetry/virtualenvs/np-py3.7/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([inf, nan, nan])

In [14]:
np.array([1.324835325123242341234, 1, 1], dtype=np.float16)

array([1.325, 1.   , 1.   ], dtype=float16)

In [6]:
print(a + b, a * b)
print(5 * b, b / 5)
print((a+b).dtype, (a*b).dtype, (5*b).dtype, (5.0*b).dtype)

[2. 1. 3.] [ 1. -2.  0.]
[ 5 -5  0] [ 0.2 -0.2  0. ]
float64 float64 int64 float64


In [15]:
print(np.dot(a, b))
print(np.matmul(a, b))
print(np.matmul(a, b.T))

-1.0
-1.0
-1.0


In [16]:
print(b, b.T)
print(b.shape)
print(b.T.shape)
print(b == b.T)

[ 1 -1  0] [ 1 -1  0]
(3,)
(3,)
[ True  True  True]


In [17]:
print(np.all(b == b))
print(a == b)
# https://docs.scipy.org/doc/numpy/reference/generated/numpy.allclose.html

True
[ True False False]


In [18]:
print(np.all(a == b))
print(np.any(a == b))

False
True


In [22]:
a[a == b]

array([1.])

In [23]:
b2 = np.array([b])
print(b2)
print(b2.shape)

[[ 1 -1  0]]
(1, 3)


In [ ]:
print(b2.T)
print(b2.T.shape)

In [24]:
np.matmul(b2, b2)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1 is different from 3)

In [26]:
np.matmul(b2, b2.T)

array([[2]])

In [27]:
np.vstack((b, b, b))

array([[ 1, -1,  0],
       [ 1, -1,  0],
       [ 1, -1,  0]])

In [28]:
np.hstack((a.T, a.T, a.T))

array([1., 2., 3., 1., 2., 3., 1., 2., 3.])

In [30]:
c = np.array([[1, 2], [3, 4]])
print(c, '\n')
print(c.T, '\n')

[[1 2]
 [3 4]] 

[[1 3]
 [2 4]] 



In [32]:
e = np.eye(2)
print(e, '\n')
print(c * e, '\n')    # element wise
print(np.matmul(c, e))

[[1. 0.]
 [0. 1.]] 

[[1. 0.]
 [0. 4.]] 

[[1. 2.]
 [3. 4.]]


In [33]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [34]:
np.ones((5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [35]:
np.arange(0, 1, 0.1), np.linspace(0, 1, 10)

(array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]),
 array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
        0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ]))

In [36]:
r = np.arange(0, 11, 2)
r

array([ 0,  2,  4,  6,  8, 10])

In [37]:
m = np.outer(r, r + 1)
m

array([[  0,   0,   0,   0,   0,   0],
       [  2,   6,  10,  14,  18,  22],
       [  4,  12,  20,  28,  36,  44],
       [  6,  18,  30,  42,  54,  66],
       [  8,  24,  40,  56,  72,  88],
       [ 10,  30,  50,  70,  90, 110]])

In [38]:
m[1,0]

2

In [39]:
m[0], m[0,:], m[:,0]

(array([0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0]),
 array([ 0,  2,  4,  6,  8, 10]))

In [40]:
m[1:,1:-1]

array([[ 6, 10, 14, 18],
       [12, 20, 28, 36],
       [18, 30, 42, 54],
       [24, 40, 56, 72],
       [30, 50, 70, 90]])

In [41]:
m[1::2,:]

array([[  2,   6,  10,  14,  18,  22],
       [  6,  18,  30,  42,  54,  66],
       [ 10,  30,  50,  70,  90, 110]])

In [43]:
[1, 2, 3, 4][1::2]

[2, 4]

In [44]:
m[:,::-1]

array([[  0,   0,   0,   0,   0,   0],
       [ 22,  18,  14,  10,   6,   2],
       [ 44,  36,  28,  20,  12,   4],
       [ 66,  54,  42,  30,  18,   6],
       [ 88,  72,  56,  40,  24,   8],
       [110,  90,  70,  50,  30,  10]])

In [45]:
m > 5 and m < 15

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [46]:
x = np.logical_and(m > 5, m < 15)
x

array([[False, False, False, False, False, False],
       [False,  True,  True,  True, False, False],
       [False,  True, False, False, False, False],
       [ True, False, False, False, False, False],
       [ True, False, False, False, False, False],
       [ True, False, False, False, False, False]])

In [47]:
m[x]

array([ 6, 10, 14, 12,  6,  8, 10])

In [48]:
m * x

array([[ 0,  0,  0,  0,  0,  0],
       [ 0,  6, 10, 14,  0,  0],
       [ 0, 12,  0,  0,  0,  0],
       [ 6,  0,  0,  0,  0,  0],
       [ 8,  0,  0,  0,  0,  0],
       [10,  0,  0,  0,  0,  0]])

In [49]:
m * ~x

array([[  0,   0,   0,   0,   0,   0],
       [  2,   0,   0,   0,  18,  22],
       [  4,   0,  20,  28,  36,  44],
       [  0,  18,  30,  42,  54,  66],
       [  0,  24,  40,  56,  72,  88],
       [  0,  30,  50,  70,  90, 110]])

In [50]:
z = np.exp([1, 2, 3])
np.e

2.718281828459045

In [51]:
np.log(z)

array([1., 2., 3.])

In [52]:
10**a, np.log10(10**a)

(array([  10.,  100., 1000.]), array([1., 2., 3.]))

In [53]:
np.pi, np.e

(3.141592653589793, 2.718281828459045)

In [54]:
y = [0, np.pi/6, np.pi/2]
np.sin(y)

array([0. , 0.5, 1. ])

In [55]:
X, Y = np.array([1, 2, 3]), np.array([110, 210, 310])
result = np.polyfit(X, Y, 1)
result

array([100.,  10.])

In [56]:
result[0] * X + result[1]

array([110., 210., 310.])